### ISSUE TITLE
Failed to activate the log-console package

### ISSUE THREAD

**Issue by kankaristo** [yongkangchen/log-console#12]
[Enter steps to reproduce below:]

1. Try to activate the `log-console` package.

**Atom Version**: 0.207.0
**System**: Ubuntu 14.04.2
**Thrown From**: [log-console](https://github.com/yongkangchen/log-console) package, v0.2.0

### Stack Trace

Failed to activate the log-console package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.LogConsole.activate (/home/sami/.atom/packages/log-console/lib/log-console.coffee:19:42)
  at doActive (/home/sami/.atom/packages/log-console/lib/main.coffee:8:9)
  at Object.module.exports.activate (/home/sami/.atom/packages/log-console/lib/main.coffee:14:5)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:238:19)
  at /usr/share/atom/resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:313:19
  at /usr/share/atom/resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:148:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:310:27)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "docblockr",
      "linter-luacheck",
      "autocomplete-clang",
      "atom-ctags",
      "linter-cpplint",
      "pigments"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-fuzzy-grep, v0.2.0
auto-detect-indentation, v0.4.2
autocomplete-glsl, v0.2.3
autocomplete-paths, v1.0.2
branch-status, v0.7.0
build, v0.36.1
clipboard-plus, v0.2.0
editor-stats, v0.17.0
external-open, v0.5.3
file-icons, v1.5.7
file-watcher, v0.3.1
flex-tool-bar, v0.4.2
git-log, v0.4.1
git-tab-status, v1.9.2
gutter-shadow, v0.4.3
highlight-line, v0.10.2
highlight-selected, v0.9.3
indentation-indicator, v0.5.1
keybinding-cheatsheet, v0.0.9
language-brainfuck, v0.1.0
language-gitignore, v0.2.0
language-glsl, v2.0.0
language-ini, v1.10.0
language-latex, v0.6.1
language-lisp, v0.1.2
language-lua, v0.9.3
language-qml, v1.0.0
language-restructuredtext, v0.6.0
language-svg, v0.8.0
language-swig, v0.1.0
language-x86, v0.1.0
line-diff-details, v1.1.1
line-jumper, v0.14.1
linter, v0.12.6
linter-clang, v2.26.0
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-flake8, v1.4.2
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-less, v0.4.0
linter-lua, v0.1.6
linter-pylint, v0.2.2
linter-shellcheck, v0.0.8
linter-xmllint, v0.0.6
log-console, v0.2.0
minimap, v4.9.4
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
open-recent, v2.2.4
overflow, v1.1.1
pretty-json, v0.3.3
project-colorize, v0.2.0
project-manager, v1.15.10
revert-buffer, v0.5.0
script, v2.23.0
svg-preview, v0.6.0
symbols-tree-view, v0.9.3
sync-settings, v0.2.2
tab-smart-sort, v0.1.4
toggle-packages, v1.0.1
tool-bar, v0.1.5
trailing-spaces, v0.3.0
tree-view-breadcrumb, v0.6.0
tree-view-open-files, v0.2.4
wakatime, v4.0.9
zentabs, v0.8.4

# Dev
atom-fuzzy-grep, v0.2.0
branch-status, v0.7.0
build, v0.36.1
tool-bar, v0.1.5
```

**Comment by kankaristo** [comment]
I started working on fixing this. There were a few deprecations here and there, nothing too major.

Still, the package seems a little broken (can't close/disable, log looks pretty weird, etc), but I have never used it before, so I don't know what it normally looks like.

**Comment by Silom** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.3
**Thrown From**: [log-console](https://github.com/yongkangchen/log-console) package, v0.2.0


### Stack Trace

Failed to activate the log-console package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.LogConsole.activate (/Users/Silom/.atom/packages/log-console/lib/log-console.coffee:21:48)
    at doActive (/Users/Silom/.atom/packages/log-console/lib/main.coffee:14:18)
    at Object.module.exports.activate (/Users/Silom/.atom/packages/log-console/lib/main.coffee:22:14)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:453:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:437:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
```

### Commands

```
  2x -0:01.1.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".min.js",
      ".map",
      ".vagrant"
    ],
    "disabledPackages": [
      "neon-selection",
      "language-objective-c",
      "language-ruby-on-rails",
      "language-toml",
      "keybinding-resolver",
      "emmet",
      "node-resolver",
      "jshint"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "projectHome": "/Users/Silom/Projects",
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
auto-update-packages, v1.0.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
file-icons, v1.6.2
jsformat, v0.9.0
language-babel, v0.10.4
language-ejs, v0.2.0
language-jade, v0.6.2
log-console, v0.2.0
minimap, v4.12.1
pigments, v0.9.2
react, v0.12.6
webbox-color, v0.5.8

# Dev
No dev packages
```
