### ISSUE TITLE
Failed to activate the log-console package

### ISSUE THREAD

**Issue by ASBaumgarten** [yongkangchen/log-console#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [log-console](https://github.com/yongkangchen/log-console) package, v0.2.0
### Stack Trace

Failed to activate the log-console package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.LogConsole.activate (/Users/Alexander/.atom/packages/log-console/lib/log-console.coffee:19:42)
  at doActive (/Users/Alexander/.atom/packages/log-console/lib/main.coffee:8:9)
  at Object.module.exports.activate (/Users/Alexander/.atom/packages/log-console/lib/main.coffee:14:5)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:370:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
  3x -6:24.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:22.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:19.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -3:15.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:12.2.0 core:select-up (atom-text-editor.editor.is-focused)
 15x -3:11.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:25.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.3
debugger, v0.0.1
language-lua, v0.9.4
linter-clang, v3.1.3
linter-pylint, v1.0.0
log-console, v0.2.0
minimap, v4.12.3
minimap-git-diff, v4.1.8

# Dev
No dev packages
```

**Comment by ASBaumgarten** [comment]
Just clicked "Install" and it failed.

**Comment by AWTrost** [comment]
Same issue

**Comment by santa222** [comment]
same issue

**Comment by yongkangchen** [comment]
Sorry, I did not maintain this package anymore.

**Comment by ASBaumgarten** [comment]
Umm... then who does?
